name: pahlevikun.github.io
description: A resume flutter app.
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.4
  get_it: ^7.6.7
  injectable: ^2.3.2
  dio: ^5.4.0
  omega_dio_logger: ^1.2.0
  json_annotation: ^4.8.1
  http: ^1.2.0
  retrofit: ^4.1.0
  rxdart: ^0.27.7
  rxdart_ext: ^0.2.9
  freezed_annotation: ^2.4.1
  fluro: ^2.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.19.0
  lottie: ^3.0.0
  image_network: ^2.5.6
  flutter_network_image: ^0.0.8
  flutter_staggered_grid_view: ^0.4.1
  adaptive_theme: ^3.6.0
  toastification: ^1.2.0
  flutter_native_splash: ^2.3.10
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.1.0
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/gif/

flutter_native_splash:
  color: "#f5ecd7"
  web: true
  color_web: "#f5ecd7"
  color_dark_web: "#f5ecd7"
  image_web: assets/gif/loading2.gif